### ISSUE TITLE
Where is the list?

### ISSUE THREAD

**Issue by gerardoepitacio** [Linkaynn/code-stats-ranking#17]
Where or how can I see the list of ranked users?
I would be great to add instructions about it.

**Comment by Linkaynn** [comment]
@gerardoepitacio 

Here is the list: https://www.jeseromero.com/code-stats-ranking/dashboard/code-staters

I just added it to README, thanks for the issue 😄

**Comment by Linkaynn** [comment]
Notice that has a really bad UI, it was a short project. I would like to rebuild from scratch it but I need to find some free time 😓

**Comment by gerardoepitacio** [comment]
Thanks!
